name: CENAOS Telegram Bot

on:
  schedule:
  - cron: 0 13 * * *
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependencias
        run: |
          pip install python-telegram-bot==20.7 python-dotenv tzdata
          pip install python-telegram-bot[job-queue]

      - name: Ejecutar bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        run: python bot_cenaos_dynamic.py

